name: Deploy to CapRover

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository }}
      CAPROVER_APP: estigmadoc
      CAPROVER_SERVER: https://captain.meapp.com.ar/
      CAPROVER_TOKEN: ${{ secrets.CAPROVER_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME

      - name: Deploy to CapRover
        uses: caprover/deploy-from-github@v1.0.1
        with:
          server: ${{ env.CAPROVER_SERVER }}
          app: ${{ env.CAPROVER_APP }}
          token: ${{ env.CAPROVER_TOKEN }}
          image: $IMAGE_NAME